#!/bin/bash

THIS_SCRIPT_DIR=$(dirname $0)
if [[ "$(basename $(dirname $(pwd -P)/../../..))" == 'dein' ]] ; then
	VIM_SCRIPT=$(basename $(pwd -P))
	SCRIPTS=("${THIS_SCRIPT_DIR}/${VIM_SCRIPT}/setup")
else
	SCRIPTS=("$(ls $THIS_SCRIPT_DIR/*/setup)")
fi
for SCRIPT_NAME in ${SCRIPTS[@]}
do
	echo $SCRIPT_NAME
	$SCRIPT_NAME
done
