""""""""""""""""""""""""""""""
" colorroller.vim
""""""""""""""""""""""""""""""
let g:colorroller_colors = [
   \'default',
   \'moss',
   \'jellybeans',
   \'softblue',
   \'tir_black',
   \'wombat256mod',
   \'yuroyoro256',
   \'molokai',
   \'desert256',
   \'mrkn256',
   \'wuye',
   \'autumn',
   \'breeze',
   \'fine_blue',
   \'fruit',
   \'neon',
   \'night',
   \'sea',
   \ ]

colorscheme autumn
