#!/bin/bash

CUR_DIR=$(cd $(dirname $0); pwd -P)
PLUGIN_NAME=$(basename $CUR_DIR)
PLUGIN_DIR=${CUR_DIR}/../../bundle/${PLUGIN_NAME}

cd $PLUGIN_DIR
cat <<PATCH | patch -p1
diff --git a/autoload/perl_local_lib_path.vim b/autoload/perl_local_lib_path.vim
index ba8e9c4..568fb3a 100644
--- a/autoload/perl_local_lib_path.vim
+++ b/autoload/perl_local_lib_path.vim
@@ -60,6 +60,7 @@ function! perl_local_lib_path#add_perl_paths(perl_paths)
   call extend(inc_paths, original_paths)
   let path_str = join(inc_paths, ',')
   execute "set path=".path_str
+  let g:syntastic_perl_lib_path = path_str
 endfunction
 
 let &cpo = s:save_cpo
PATCH
cd $CUR_DIR
