#!/bin/bash

CUR_DIR=$(cd $(dirname $0); pwd -P)
PLUGIN_NAME=$(basename $CUR_DIR)
PLUGIN_DIR=${CUR_DIR}/../../bundle/${PLUGIN_NAME}

cd ${PLUGIN_DIR}/ftplugin
for FT in html tt2 xslate tt2html
do
	if ! [ -s $FT.vim ] ; then
		ln -s xml.vim $FT.vim
	fi
done

perl -i -ne '/<LocalLeader>x/ or print $_' xml.vim
