#!/bin/bash

# analize_slowquery.sh
#   Purpose: skelton of shell script
#
#   Author: Yusuke Wtase <ywatase@gmail.com>

MAILTO=
TMPFILE=/tmp/slow-log.`date "+%s"`.log
MAIL=`which mail`
CAT=cat

VERSION=0.1

main () {
  init "$@"
  # write here
  echo "${GROUP} servers summary" > ${TMPFILE}
  echo >> ${TMPFILE}
  
  ## master
  for TARGET in ${HOST_MASTER}
  do
      echo "${TARGET} ----------" >> ${TMPFILE}
        ssh ${TARGET} "$CAT ${SLOWLOG_PATH}" | pt-query-digest >> ${TMPFILE}
          echo >> ${TMPFILE}
        done
  
  ## slave
  for TARGET in ${HOST_SLAVE}
  do
      echo "${TARGET} ----------" >> ${TMPFILE}
        ssh ${TARGET} "$CAT ${SLOWLOG_PATH}" | pt-query-digest >> ${TMPFILE}
          echo >> ${TMPFILE}
        done
  
  ## mail
  if [ "$MAILTO" != "" ] ; then 
    _send_mail
  fi
  rm -f ${TMPFILE}
}

init () {
  while getopts 'g:m:p:vt:' opt
  do
    case $opt in
      g) GROUP=$OPTARG
        ;;
      t) MAILTO=$OPTARG 
        ;;
      m) HOST_MASTER=$OPTARG 
        ;;
      p) SLOWLOG_PATH=$OPTARG
        ;;
      v) show_version; usage 
        ;;
      *) usage 
        ;;
    esac
  done
  shift `expr $OPTIND - 1`

  HOST_SLAVE=("$@")

  if [ "$MAILTO" == "" ] || [ "$SLOWLOG_PATH" == "" ] || [ "$GROUP" == "" ] ; then
    usage
  fi
  if [ "$HOST_MASTER" == "" ] && [ "$HOST_SLAVE" == "" ] ; then
    usage
  fi

  if [[ $SLOWLOG_PATH =~ \.gz$ ]] ; then
    CAT=zcat
  fi

}

usage () {
	/bin/cat <<END
usage: `basename $0` [-tgmv] [slave1] [slave2] [...]
  t mail_adderss : send to mail_address
  g group_name   : service group name
  m master       : master server
  v              : show version
END
	exit 0
}

_send_mail () {
  /bin/cat ${TMPFILE} | $MAIL -s "Summary of slow-query ${GROUP}" $MAILTO
}

show_version () {
	echo -e `basename $0` Version: $VERSION
}


main $@

# vim:set ts=2 et sw=2 si:
