#!/bin/bash

# analyze_slowquery
#   Purpose: analyze slowquery by pt-query-digest
#
#   Author: Yusuke Wtase <ywatase@gmail.com>
#           hatak

MAILTO=
TMPFILE=/tmp/slow-log.`date "+%s"`.log
CMD_MAIL=mail
CMD_CAT=cat
CMD_PTQD=pt-query-digest
SLOWLOG=/var/lib/mysql/mysql-slow.log
TARGET_HOSTS=()


VERSION=0.1

main () {
  init "$@"
  # write here
  echo "${GROUP} servers summary" > ${TMPFILE}
  echo >> ${TMPFILE}
  
  for (( I = 0; I < ${#TARGET_HOSTS[@]}; ++I ))
  do

      echo "${TARGET_HOSTS[$I]} ----------" >> ${TMPFILE}
        ssh ${TARGET_HOSTS[$I]} "${CMD_CAT} ${SLOWLOG}" | ${CMD_PTQD} >> ${TMPFILE}
          echo >> ${TMPFILE}
        done
  
  ## mail
  if [ "$MAILTO" != "" ] ; then 
    send_mail
  fi
  rm -f ${TMPFILE}
}

init () {
  while getopts 'g:m:p:v' opt
  do
    case $opt in
      g) GROUP=$OPTARG
        ;;
      m) MAILTO=$OPTARG 
        ;;
      p) SLOWLOG_PATH=$OPTARG
        ;;
      v) show_version; usage 
        ;;
      *) usage 
        ;;
    esac
  done
  shift `expr $OPTIND - 1`

  TARGET_HOSTS=("$@")

  if [ "$MAILTO" == "" ] ; then
    echo "set -m mail_address"
    usage
  elif [ "$GROUP" == "" ] ; then
    echo "set -g group"
    usage
  elif [ ${#TARGET_HOSTS[@]} -eq 0 ] ; then
    echo "set target host"
    usage
  fi

  if [[ $SLOWLOG_PATH =~ \.gz$ ]] ; then
    CAT=zcat
  fi

}

usage () {
	/bin/cat <<END
usage: `basename $0` [-tgv] [host1] [host2] [...]
  p slowlog_path : path to slow log  (default: ${SLOWLOG_PATH})
  m mail_adderss : send to mail_address
  g group_name   : service group name
  v              : show version

  ex) analyze_slowquery -p '/var/lib/mysql/mysql-slow.log.1' -m curry@example.com -g food [host1] [host2] ...

END
	exit 0
}

send_mail () {
  cat ${TMPFILE} | $CMD_MAIL -s "Summary of slow-query ${GROUP}" $MAILTO
}

show_version () {
	echo -e `basename $0` Version: $VERSION
}


main "$@"

# vim:set ts=2 et sw=2 si:
