###
# Set shell options
##
setopt auto_menu auto_cd auto_pushd correct auto_name_dirs auto_remove_slash
setopt pushd_ignore_dups rm_star_silent sun_keyboard_hack
setopt extended_glob list_types no_beep always_last_prompt
setopt cdable_vars sh_word_split auto_param_keys
# 補完リストその他でもASCII(7ビット)以上の文字(8ビット)文字を表示 
# # (マルチバイト文字補完)
setopt PRINT_EIGHT_BIT

autoload -Uz is-at-least

###
# enable auto complete 
###
fpath=($HOME/.zsh/functions(N-/) $fpath)
if is_mac ; then
  path=($HOME/bin(N-/) $HOME/bin/*(N-/) /usr/local/bin $path)
fi

typeset -U fpath
typeset -U path
autoload -U compinit
if is_cygwin ; then
  compinit -u
else
  compinit
fi

###
# antigen
###
source $HOME/.zsh/zshrc.antigen


###
# Alias
###
alias l=ls
if is_mac ; then
  if which gls >/dev/null 2>&1 ; then
    alias ls="gls --color=auto --show-control-chars"
  else
    alias ls="ls -G"
  fi
  if which gtar >/dev/null 2>&1 ; then
    alias tar=gtar
  fi
  alias "clang++11"="clang++ -std=c++11 -stdlib=libc++ -Weverything"
  alias netstat_osx='sudo lsof -i -P'
  alias mac_dot_files_visible="defaults write com.apple.finder AppleShowAllFiles -bool YES;killall Finder"
  alias mac_dot_files_invisible="defaults write com.apple.finder AppleShowAllFiles -bool NO;killall Finder"
  alias mac_set_tcp_delayed_ack_0="sudo sysctl -w net.inet.tcp.delayed_ack=0"
  mac_dashboad_off() {
    echo "DASHBOARD OFF"
    mac_dashboard-toggle "true"
  }

  mac_dashboad_on() {
    echo "DASHBOARD ON"
    mac_dashboard-toggle "false"
  }
  mac_dashboard_toggle() {
    if $1 = "true" ; then
      defaults write com.apple.dashboard mcx-disabled -boolean true
    else
      defaults write com.apple.dashboard mcx-disabled -boolean false
    fi
    killall Dock
  }
else
  alias ls="ls --color=auto --show-control-chars"
fi
alias la="ls -aF"
alias ll="ls -l"
alias psn="ps auxf | perl -pe 's/^\\s*(\\d+)/sprintf qq{%-10s}, substr(scalar(getpwuid(\$1)), 0, 10)/e;'"
alias rdesk="rdesktop -r clipboard -zP -ken-us"
alias rdesk_full="rdesk -f"
alias git-submodule-pull="git submodule foreach 'git checkout master; git pull'"
alias git-submodule-fetch="git submodule foreach 'git checkout master; git fetch'"
alias get_viplugin="lftp -u viplugin,667well www.satokar.com"
alias start_selenium_server='java -jar /home/watase/selenium-server/selenium-server.jar'
alias make_patch='diff -u --strip-trailing-cr -B -w'
alias delete_proxy_env='unset HTTP_PROXY HTTPS_PROX http_proxy https_proxyy'
# autojump
if [ -e $HOME/.zsh/z.git/z.sh ] ; then
  _Z_CMD=j
  source $HOME/.zsh/z.git/z.sh
fi

alias -g V='| vim -'
alias -g G='| grep '
alias -g L='| less'
alias -g T='| tail -f'
alias -g SPLIT="| perl -le 'map{chomp;print+join\"\\n\",split/\$ARGV[0]/}<STDIN>'"
alias -g JOIN="| perl -le 'print+join\"\$ARGV[0]\",(map{chomp;\$_}<STDIN>)'"
alias -g C='| colorize-http-status.sed'

alias dstat-full='dstat -Tclmdrn'
alias dstat-mem='dstat -Tclm'
alias dstat-cpu='dstat -Tclr'
alias dstat-net='dstat -Tclnd'
alias dstat-disk='dstat -Tcldr'

_SUDO=sudo
# for windows
if is_cygwin ; then
  _SUDO=''
  alias vi=vim
  alias gvim=/usr/local/vim/gvim
  alias traceroute="tracert"
  alias svn="LANG=C LC_ALL=C svn"
fi

if is_host "pc-igademo" ; then
#  export LANG=C
  export GIT_PROXY_COMMAND=$HOME/bin/git-proxy
  alias svn="LANG=ja_JP.UTF-8 LC_ALL=ja_JP.UTF-8 svn"
fi

# mysql prompt
export MYSQL_PS1='MySQL \v [1;33m\u[0m@[1;35m\h[0m/[1;31m\d[0m [1;33m[\R:\m:\s][0m\nmysql\c>'
# ssh agent
if is_ssh_client && ! is_screen && ! is_tmux ; then
  keychain ~/.ssh/id_dsa
  source ~/.keychain/$HOST-sh
fi
agent="$HOME/tmp/ssh-agent-$USER"
if [ -S "$SSH_AUTH_SOCK" ] ; then
  case $SSH_AUTH_SOCK in
    /tmp/*/agent.[0-9]*)
      if ! [ -e "$HOME/tmp" ] ; then
        mkdir "$HOME/tmp"
      fi
      ln -snf "$SSH_AUTH_SOCK" $agent && export SSH_AUTH_SOCK=$agent
  esac
elif [ -S $agent ]; then
  export SSH_AUTH_SOCK=$agent
else
  echo "no ssh-agent"
fi

recovery_ssh_auth_sock_if_lost_sock () {
  if [ -S $SSH_AUTH_SOCK ] ; then
    return
  fi
  netstat -lnx | perl -ne 'print "$1\n" if m|(/tmp/ssh-.+/agent.+)|' | while read agent
  do
    if [ -r $agent ] ; then
      echo "link: '$agent' to '$SSH_AUTH_SOCK'"
      ln -fs $agent $SSH_AUTH_SOCK
      export SSH_AUTH_SOCK
      break
    fi
  done
  echo "Error: agent socket is not found."
}

###
# mac
###
if is_mac ; then
  install-homebrew () {
    /usr/bin/ruby -e "$(curl -LfsS https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  }
  brew-make-alias-of-coreutils () {
    brew ls coreutils 2>&1| grep /bin/g | perl -lne 'chomp; m{/bin/g(\w+)$} and print sprintf q{alias %s=g%s}, $1, $1 ' >> ~/.zsh/zshenv_coreutils_alias
  }
  install-vim () {
    brew install https://raw.github.com/AndrewVos/homebrew-alt/master/duplicates/vim.rb
    mv /usr/bin/vim /usr/bin/vim72
  }
  install-q4m-dev () {
    zsh -c "$(curl -fsSL https://raw.github.com/gist/1426403)"
  }
fi


###
# screen
###
if is_screen || is_tmux ; then
    preexec() {
        # see [zsh-workers:13180]
        # http://www.zsh.org/mla/workers/2000/msg03993.html
        emulate -L zsh
        local -a cmd; cmd=(${(z)2})
        case $cmd[1] in
            fg)
                if (( $#cmd == 1 )); then
                    cmd=(builtin jobs -l %+)
                else
                    cmd=(builtin jobs -l $cmd[2])
                fi
                ;;
            %*)
                cmd=(builtin jobs -l $cmd[1])
                ;;
            ls|gls)
                return
                ;; 
            cd)
                if (( $#cmd == 2)); then
                    cmd[1]=$cmd[2]:t
                else
                    cmd[1]="~"
                fi
                change_status_title $cmd[1]
                prev=$cmd[1]
                return
                ;;
            vim|vi|gvim|sh|perl|bash)
                if (( $#cmd == 2)); then
                  cmd[1]="$cmd[1]:$cmd[2]:t"
                fi
                change_status_title $cmd[1]
                prev=$cmd[1]
                return
                ;;
            *)
                change_status_title $cmd[1]:t
                prev=$cmd[1]
                return
                ;;
        esac
        local -A jt; jt=(${(kv)jobtexts})
        $cmd >>(read num rest
            cmd=(${(z)${(e):-\$jt$num}})
            change_status_title $cmd[1]:t) 2>/dev/null
        prev=$cmd[1]
    }
#    precmd() {
#        change_status_title $:$prev:t
#    }
    change_status_title() {
      echo -n "k$1\\"
    }
fi 


if is_screen ; then
  function ssh_screen(){
    eval server=\${$#}
    recovery_ssh_auth_sock_if_lost_sock
    screen -t $server env SSH_AUTH_SOCK="$SSH_AUTH_SOCK" ssh "$@"
  }
  alias ssh=ssh_screen
  compdef _ssh ssh_screen=ssh
elif is_tmux ; then
  function ssh_tmux() {
    eval server=\${$#}
    recovery_ssh_auth_sock_if_lost_sock
    tmux neww -n $server "exec ssh $@"
  }
  function man_tmux() {
    tmux split-window "exec man $@"
  }
  alias ssh=ssh_tmux
  compdef _ssh ssh_tmux=ssh
  compdef _man man_tmux=man
fi

# cdd
source $HOME/.zsh/cdd
function chpwd() {
  if is_tmux ; then
    _reg_pwd_screennum
    tmux setenv TMUXPWD_$(tmux display -p "#I") $PWD
  elif is_screen ; then
    _reg_pwd_screennum
  fi
}
# //cdd



function ssh_resolve_cname () {
    TARGET=`host $1 | perl -e '$a=join q{},<>;$a=~m/is an alias for ([^\s]+)/; print $1'`
  if [ x$TARGET = x ] ; then
    ssh $@
  else
    shift
    echo $TARGET
    ssh $@ $TARGET
  fi
}

# ec2
ec2_get_metadata () {
  curl -s http://169.254.169.254/latest/meta-data/
}

r() {
  local f
  f=(~/.zsh/functions/*(.))
  unfunction $f:t 2> /dev/null
  autoload -U $f:t
  compinit -u
}

###
# Environment variable
###
if is_mac  ; then
# avoid "/usr/bin/vim" exit code bug.
# if setting EDITOR=vim, /usr/bin/vim sometimes return 1 and fail to edit cron, commit log and so on
  export EDITOR=/usr/bin/vim
else
#  for nodelint-vim
  if which nodelint | grep '.nvm' >/dev/null 2>&1 ; then
    export NODE_PATH=$(cd $(dirname $(which nodelint))/..;echo $(pwd -P)/lib/node_modules)
  fi 
  eval `dircolors -b` # set LS_COLORS
  export EDITOR=vim
fi
export PAGER='less -R'
export TZ=JST-9
export CVS_RSH=ssh
export SVN_SSH=ssh
export WORDCHARS='i*?_-.[]~=&;!#$%^(){}<>'
umask 022

bindkey -e             # emacs key bindings
#bindkey -v             # vi key bindings
bindkey ' ' magic-space  # also do history expansion on space
bindkey "^?" backward-delete-char # delete for debian


###
# keybord-history
###
HISTFILE=$HOME/.zsh-history           # 履歴をファイルに保存する
HISTSIZE=100000                       # メモリ内の履歴の数
SAVEHIST=100000                       # 保存される履歴の数
setopt extended_history               # 履歴ファイルに時刻を記録
setopt share_history
setopt hist_ignore_dups hist_ignore_space
function history-all { history -E 1 } # 全履歴の一覧を出力する
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

###
# predict
###
#autoload predict-on
#predict-on

###
# command auto complete
###
zstyle ':completion:*:default' menu select=1
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}  # color 
zstyle ':completion:*' use-cache true
# add knows_host to hosts completion (sneed HashHostKey no at .ssh/config)
zstyle -e ':completion::*:*:*:hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'

# This file gives some examples of compctl commands.
# You can either put the compctl commands in your .zshrc
# or include a separate file from your .zshrc with the
# source command.

###
# complete database
###
# All completions for zsh.
# Some builtins.
compctl -j -P % fg bg wait jobs disown
compctl -A shift
compctl -caF whence which
compctl -F unfunction
compctl -a unalias
compctl -v unset typeset declare vared readonly export integer
compctl -e disable
compctl -d enable
compctl -k '(cputime filesize datasize stacksize coredumpsize resident \
  memoryuse memorylocked descriptors openfiles vmemorysize)' limit u{n,}limit
compctl -l '' -x 'p[1]' -f -- . source

###
# for directory operators
###
# Rmdir only real directories
compctl -g '(|.)*(-/)' rmdir dircmp rd mdcd mkdir
compctl -x 'p[2]' -k "(wheel staff ftpadmin okoma)"  -- pubmd

# vim:set ts=2 sw=2 et si:
